### ISSUE TITLE
Lady Deathwhisper - Valithria Dreamwalker

### ISSUE THREAD

**Issue by Noob1e** [Ayaro1/DBM_Warmane_Icecrown#2]
### Lady Deathwhisper:
Mind Control casts are mostly delayed compared to the DBM timer. It usually delays 0.5-1 second, but the first delay is 1.5-2 seconds.
It gets better at the 4th cast. But getting back to 1.5-2 seconds after the 4th cast.
1st: https://www.twitch.tv/videos/734288656?t=0h21m55s
2nd: https://www.twitch.tv/videos/734288656?t=0h22m40s
3rd: https://www.twitch.tv/videos/734288656?t=0h22m40s
4th: https://www.twitch.tv/videos/734288656?t=0h22m40s
5th (1st): https://www.twitch.tv/videos/734288656?t=0h24m44s
### Valithria Dreamwalker:
2nd wave of suppressor timer is wrong.
https://www.twitch.tv/videos/734288656?t=1h27m59s

**Comment by Ayaro1** [comment]
Just checked one of my own kill vids to see timers on Lady Deathwhisper for comparison to the videos linked above.
https://www.twitch.tv/videos/732691402?t=0h12m15s
The timer for the first MC is indeed a little too early. This has now been adjusted.
As for the ones later on, some are on point in my vid, some are off with 0.5-1 second.
This is mostly because of Warmane's spellque system.

As for Valithria Dreamwalker.
https://www.twitch.tv/videos/731680512?t=2h12m20s (watch me gloriously afk parts of the fight)
I understand why you think that timer is wrong, but it's not.
The second wave just doesn't spawn at all. Thank you Warmane.
There is supposed to be and used to be a wave of Suppressors there.
I'm leaving that timer in place as it is for if and when Warmane decides to suddenly fix this.
I highly doubt that'll be soon tho as it's a bug that's not hurting anyone so i'm guessing not a whole lot of people will report the issue to the bug tracker.
